from collections import defaultdict
student_grades = defaultdict(list)
for name, grade in grades:
    student_grades[name].append(grade)


from collections import Counter
words = "if there was there was but if there was not there was not".split()
counts = Counter(words)
# Counter({'if': 2, 'there': 4, 'swas': 4, 'not': 2, 'but': 1})

Node currentNode = inputNode
continue = True
if currentNode == null
Continue = False
return null;
key = inputNode.key
while (key  currentNode.key and currentNode.parent != null):
    if(key > currentNode.left.key and key > currentNode.right.key)
        if currentNode.key > key and currentNode.key < currentNode.parent.key
            return currentNode
            break;
        else
            currentNode = currentNode.parent
            continue
    if key < currentNode.left.key
        currentNode = currentNode.left
        continue
    if key < currentNode.right.key
        currentNode = currentNode.right.key

current
